name: Build

on:
  push:
    branches-ignore:
      - 'main'
      - 'dependabot/**'
    tags-ignore:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  call-workflow:
    name: Centralized workflow
    uses: flighttrackr/workflows/.github/workflows/build-with-upstream.yml@main
    with:
      hub_repo: flighttrackr
      hub_image: mlat-client
      image_authors: Dennis Neufeld <git@dneufeld.net>
      image_title: mlat-client
      image_description: Dockerized mlat-client
      image_licenses: MIT
