name: Build, Push, Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  call-workflow:
    name: Centralized workflow
    uses: flighttrackr/workflows/.github/workflows/release-with-upstream.yml@main
    with:
      hub_repo: flighttrackr
      hub_image: mlat-client
      image_authors: Dennis Neufeld <git@dneufeld.net>
      image_title: mlat-client
      image_description: Dockerized mlat-client
      image_licenses: MIT
